### ISSUE TITLE
NPE on /chat/Hello

### ISSUE THREAD

**Issue by fatlotus** [codeu-2018-team12/codeu-2018-team12#102]
```
com.google.apphosting.runtime.jetty9.JettyLogger warn: /chat/Hello
java.lang.NullPointerException
	at codeu.model.data.User.addConversationFriend(User.java:229)
	at codeu.controller.ChatServlet.addConversationFriends(ChatServlet.java:281)
	at codeu.controller.ChatServlet.joinConversation(ChatServlet.java:377)
	at codeu.controller.ChatServlet.doPost(ChatServlet.java:173)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
```

**Comment by Mariamcm90** [comment]
I looked into the NPE and it was caused by the addConversationFriend/removeConversationFriend methods being called on a user that was deleted from Datastore. I added a null pointer check but now the conversations that were having the issue won't load at all. I'm a bit confused as to why because the line that's being pointed to in the logs seems fine ( it's  <form id="chatform" action="/chat/<%= conversation.getTitle() %>" method="POST" enctype='multipart/form-data'>, but we do a null pointer check in the servlet for the conversation). I will look more into it!
