### ISSUE TITLE
The datastore doesn't seem to like old entities

### ISSUE THREAD

**Issue by fatlotus** [codeu-2018-team12/codeu-2018-team12#71]
I tried to deploy from `master` today and got some errors:

```
com.google.apphosting.runtime.jetty9.JettyLogger warn: Failed startup of context c.g.a.r.j.AppEngineWebAppContext@c3f009d{/,file:///base/data/home/apps/d~chatu-196017/1.408882357831059668/,UNAVAILABLE}{/base/data/home/apps/d~chatu-196017/1.408882357831059668} (JettyLogger.java:29)
java.lang.RuntimeException: codeu.model.store.persistence.PersistentDataStoreException: java.lang.NullPointerException
	at codeu.controller.ServerStartupListener.contextInitialized(ServerStartupListener.java:43)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.createHandler(AppVersionHandlerMap.java:244)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.getHandler(AppVersionHandlerMap.java:182)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:97)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:680)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:642)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:612)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:806)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)
Caused by: codeu.model.store.persistence.PersistentDataStoreException: java.lang.NullPointerException
	at codeu.model.store.persistence.PersistentDataStore.loadConversations(PersistentDataStore.java:119)
	at codeu.model.store.persistence.PersistentStorageAgent.loadConversations(PersistentStorageAgent.java:79)
	at codeu.controller.ServerStartupListener.contextInitialized(ServerStartupListener.java:30)
	... 19 more
Caused by: java.lang.NullPointerException
	at codeu.model.data.Conversation.setUsers(Conversation.java:103)
	at codeu.model.store.persistence.PersistentDataStore.loadConversations(PersistentDataStore.java:113)
	... 21 more
```

@kkane098 suspects that the startup code assumes all conversations have a `users` field.

**Comment by fatlotus** [comment]
I think this was fixed by #75.
